apiVersion: v1
kind: Pod
metadata:
    name: test-get-pods 
spec:
    containers:
    - name: test-pod
      image: beekman9527/kubelet-pod:latest 
      imagePullPolicy: Always
      args:
      - --v=4
      - --kubeletHttps=false
      - --kubeletPort=10255
