apiVersion: v1
kind: Pod
metadata:
    name: test-kubelet-1 
spec:
    containers:
    - name: kubelet-pod
      image: beekman9527/kubelet-pod:latest 
      imagePullPolicy: Always
      args:
      - --v=4
      - --kubeletPort=10255
