apiVersion: v1
kind: Pod
metadata:
  name: nodes-pods 
spec:
  serviceAccount: turbo-user
  containers:
  - name: test-pod
    image: beekman9527/kubelet-pod:latest 
    imagePullPolicy: Always
    args:
    - --v=4
    - --kubeletHttps=false
    - --kubeletPort=10255
