apiVersion: v1
kind: ServiceAccount
metadata:
  name: turbo-user
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: turbo-all-binding
subjects:
- kind: ServiceAccount
  name: turbo-user
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: test-get-pods2 
spec:
  serviceAccount: turbo-user
  containers:
  - name: test-pod
    image: beekman9527/kubelet-pod:latest 
    imagePullPolicy: Always
    args:
    - --v=4
    - --kubeletHttps=true
    - --kubeletPort=10250
